SynthesizedAutomaton automaton

# System name, e.g. "atlas"
string system

---

vigir_be_core/StateInstantiation[] state_definition

# Errors when trying to generating StateInstantiations
BSErrorCodes error_code
