# Formula in the GR(1) fragment of LTL

# System atomic propositions
string[] sys_props

# Environment atomic propositions
string[] env_props

# System initial conditions
string[] sys_init

# Environment initial conditions
string[] env_init

# System safety requirements
string[] sys_trans

# Environment safety assumptions
string[] env_trans

# System liveness requirements
string[] sys_liveness

# Environment fairness assumptions
string[] env_liveness
